### ISSUE TITLE
Titlebar does not respect GTK button position

### ISSUE THREAD

**Issue by WittyNameHere** [flathub/com.microsoft.Edge#104]
Hello again,

The official RPM release of Edge respects putting the close/minimize/maximize buttons on the left side of the window, adjusting the Tab Actions Menu as seen in this picture:

![Screenshot_20211221_122743](https://user-images.githubusercontent.com/45863172/146993736-780e2dea-016d-46db-bd99-3e495688a8bf.png)

The Flatpak release isn't doing this, keeping the buttons on the right corner in a Windows-style configuration.

Button layout data for verification:

```
$ dconf read /org/gnome/desktop/wm/preferences/button-layout
'close,minimize,maximize:'
```

**Comment by TheEvilSkeleton** [comment]
I don't want to be that guy but it works completely fine for me. Although, the output of that command is a bit different for me:

```
$ dconf read /org/gnome/desktop/wm/preferences/button-layout
'close,minimize,maximize:appmenu'
```

Notice the `appmenu` here. Did you use GNOME Tweaks to change the titlebar buttons?

**Comment by WittyNameHere** [comment]
My apologies, it turns out this was sort of a "me problem." Alas, logging out of KDE and back in restored the traffic buttons to where they should be, but now the global menu from our last issue is gone again.

I suppose this issue should be closed and the previous one re-opened, though I'm going to take a much more passive approach herein because it's pretty clear at this point I'm no coder and barely understand what's going on behind the superficial layer of software. :)
