### ISSUE TITLE
Flatpak does not pin to latte-dock (fix/workaround included)

### ISSUE THREAD

**Issue by WittyNameHere** [flathub/com.microsoft.Edge#105]
The Edge flatpak can not be pinned to Latte dock (a docky/OSX style dock that is particularly used on Plasma systems). If you right click the icon to pin it as usual, the Pin App icon is greyed out. Though I don't use Plasma's own launcher, I've heard this can affect it, too.

Fortunately, I figured a workaround, but with some caveats, and so I'm explaining this upstream so that maybe if something can be changed it'll become easier. And if not, you can at least refer to this. The workaround is that the file `/etc/xdg/taskmanagerrulesrc` which normally [looks like this](https://github.com/KDE/plasma-workspace/blob/master/libtaskmanager/taskmanagerrulesrc) needs this extra line added under the Mapping settings:

> `Microsoft-edge-beta=Microsoft Edge (beta)`

After saving this file, the app can be pinned normally. I discovered this after researching the [same issue affecting GIMP](https://bugs.kde.org/show_bug.cgi?id=408953) and running the suggested `xprop` command on this issue. The returned string is `WM_CLASS(STRING) = "microsoft-edge-beta", "Microsoft-edge-beta"` and with that it was elementary to add a new line to the taskmanagerrulesrc file.

I'm not sure if this is something that needs to be implemented upstream, I leave that to project leadership since I know this one is close to adding a stable branch.

**Comment by tinywrkb** [comment]
Copy the desktop file from `FLATPAK_INSTALLATION/app/com.microsoft.Edge/current/active/files/share/applications/com.microsoft.Edge.desktop` into `~/.local/share/applications/`, where `FLATPAK_INSTALLATION` is `/var/lib/flatpak` or `~/.local/share/flatapk`.

Add the line`StartupWMClass=microsoft-edge-beta` to the desktop file, and see if it helps. Maybe also try to log out and log in, and then test.

**Comment by WittyNameHere** [comment]
Causes a failure to launch with the error:
Could not find the program '/app/bin/edge'

**Comment by tinywrkb** [comment]
Oh! Right. Use the one from the export folder:`app/com.microsoft.Edge/current/active/export/share/applications/

**Comment by WittyNameHere** [comment]
Doing this allows me to launch the app that I have pinned to the dock while using the task manage rule edit and the app will start instead of providing the error. But it does not allow me to pin the unpinned version of the app. As soon as I remove the pin, the Edge icon goes to the end of the Dock with the other temporary program icons, and repinning it is impossible.

**Comment by WittyNameHere** [comment]
Okay, so for the benefit of those following by email: I deleted my prior comment because I forgot to make the edit to the .desktop file before firing replies, however after making that edit, nothing has changed. Using the .desktop file from the export folder will launch the program properly, but if unpinned it can't be pinned to 

dock. It can only be pinned while the task manager rule is in effect.

[edgedesktop.txt](https://github.com/flathub/com.microsoft.Edge/files/7772144/edgedesktop.txt)
Here's the contents of my desktop file for reference. The addition was added on line 109.

**Comment by TheEvilSkeleton** [comment]
> Fortunately, I figured a workaround, but with some caveats, and so I'm explaining this upstream so that maybe if something can be changed it'll become easier. And if not, you can at least refer to this. The workaround is that the file `/etc/xdg/taskmanagerrulesrc` which normally [looks like this](https://github.com/KDE/plasma-workspace/blob/master/libtaskmanager/taskmanagerrulesrc) needs this extra line added under the Mapping settings:
> 
> > `Microsoft-edge-beta=Microsoft Edge (beta)`

I don't have a KDE Identity, so sadly I can't open a merge request over there.

**Comment by TheEvilSkeleton** [comment]
Fixed by https://github.com/flathub/com.microsoft.Edge/pull/114.
