### ISSUE TITLE
Gnome software says that org.freedesktop.Platform/x86_64/20.08 is missing

### ISSUE THREAD

**Issue by nexeleriot** [flathub/com.microsoft.Edge#11]
When I open gnome software it shows me this message
![Снимок экрана от 2021-02-06 15-55-51](https://user-images.githubusercontent.com/70663363/107119510-17972b00-6899-11eb-88e8-8c824376828e.png)

In english it says that it can't find org.freedesktop.Platform/x86_64/20.08 runtime for Edge
But it is installed in my system

**Comment by TheEvilSkeleton** [comment]
Are you installing Edge in your user or in your system? Maybe you do not have `org.freedesktop.Platform/x86_64/20.08` installed in where you are installing in.

**Comment by nexeleriot** [comment]
That's it, thanks. After I installed Edge in my system message no longer appears
