### ISSUE TITLE
Entire screen sharing doesn't work on Fedora 35

### ISSUE THREAD

**Issue by ma3yta** [flathub/com.microsoft.Edge#115]
It can be checked on https://www.webrtc-experiment.com/Pluginfree-Screen-Sharing/ .

![Screenshot from 2022-01-26 14-33-26](https://user-images.githubusercontent.com/660379/151163702-75bc78e6-fdef-44b3-9c09-2e2137858729.png)

**Comment by TheEvilSkeleton** [comment]
Are you using Wayland or X11?

**Comment by ma3yta** [comment]
@TheEvilSkeleton  My system uses Wayland but I believe that MS Edge is rendered using XWayland. I tried to disable ``socket=x11`` using Flatseal but Edge stops running after that.

**Comment by ma3yta** [comment]
@TheEvilSkeleton enabling edge://flags/#enable-webrtc-pipewire-capturer resolved the issue

**Comment by TheEvilSkeleton** [comment]
What happens when you run it without `--enable-features=UseOzonePlatform --ozone-platform=wayland`?

**Comment by ma3yta** [comment]
@TheEvilSkeleton It works fine with command ``flatpak run com.microsoft.Edge -enable-features=WebRTCPipeWireCapturer``

**Comment by Dejv311** [comment]
Hi, I hate to resurrect this issue, but I still have problems with screen sharing on edge. Edge first asks Ubuntu for permission, then it shows a black screen thumbnail and after clicking "Share" microsoft edge commits suicide (crashes gloriously).

I am running the latest version of Edge on PopOs with Wayland. My desktop file is:

`Exec=/usr/bin/microsoft-edge-stable %U --enable-features=UseOzonePlatform,TouchpadOverscrollHistoryNavigation,WebRTCPipeWireCapturer --ozone-platform=wayland`

![image](https://user-images.githubusercontent.com/46622252/232307957-53b5e187-1476-4b7c-871a-10bfa2da5fe2.png)

**Comment by evan-a-a** [comment]
@iamashwin99 MS broke something related to WebRTC screen sharing in Edge 131. This impacts the non-flatpak version too. As of now it has not been fixed.
