### ISSUE TITLE
install org.freedesktop.Platform.Locale as dependency

### ISSUE THREAD

**Issue by seal20** [flathub/com.microsoft.Edge#127]
Hi,

I am using this edge flatpak to access teams, skype, onedrive, etc. on Fedora 35. The runtime org.freedesktop.Platform.Locale should be installed as a dependency to allow opening files with utf-8 (here japanese) filenames.

Flatpak 1.12.6

    flatpak info com.microsoft.Edge

    Microsoft Edge - Introducing the new Microsoft Edge web browser. It’s time to
    expect more. More privacy. More control. More productivity. More value.

          ID: com.microsoft.Edge
         Ref: app/com.microsoft.Edge/x86_64/beta
        Arch: x86_64
      Branch: beta
     Version: 99.0.1150.30-1
     License: LicenseRef-proprietary
      Origin: flathub-beta
    Collection: org.flathub.Beta
    Installation: system
     Installed: 26.4 MB
     Runtime: org.freedesktop.Platform/x86_64/21.08
         Sdk: org.freedesktop.Sdk/x86_64/21.08

      Commit: 6dd4f09f43eb7e7713cf36249a9321be334d93536f6cfcf30d6178c181f69dd0
      Parent: c5da92cf607b4a55ad73f83b7c1f04ece1c75a39c7c5400a828746ff2b6d9814
     Subject: Update edge.deb to 99.0.1150.30-1 (f147cdd3)
        Date: 2022-03-02 20:33:39 +0000

My locale is the following:

`locale
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=ja_JP.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT=ja_JP.UTF-8
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=`

When I try to send a file that has a japanese name in teams, it fails with "file empty" or "not valid". I had to install org.freedesktop.Platform.Locale so it works. An easy reproducible example.

Without org.freedesktop.Platform.Locale installed
1. Drag and drop the attached file テスト.txt on an edge window.
2. The file is not open, instead the contents of the / directory of the flatpak is opened.
![image](https://user-images.githubusercontent.com/6326493/158293339-9061ce04-e317-45de-abb9-1fe9107a6335.png)

With org.freedesktop.Platform.Locale installed
1. Drag and drop the attached file テスト.txt on an edge window.
2. The file is open and the content (this is a テスト) is shown.
![image](https://user-images.githubusercontent.com/6326493/158293486-194b6c7c-e85a-46e7-9a77-e4fb3458aa8d.png)

Attachement: File with a japanese name (it reads "test.txt")
[テスト.txt](https://github.com/flathub/com.microsoft.Edge/files/8249655/default.txt)
.

**Comment by TheEvilSkeleton** [comment]
The locales should be installed automatically.

Can you tell me what Flatpak version you arerunning (`flatpak --version`)? Also, does it only happen with Edge or with other programs too?

**Comment by seal20** [comment]
Flatpak 1.12.6 under Fedora 35.

I have seen it is happening also in Teams preview but not in inkscape for example. But the file picker is different too so I am not sure if it is a difference in the portal used. I will ask a colleague next Tuesday (sorry Monday is holiday) who doesn't have any flatpak opened to see if it works (pull the locale) on his fedora system. It is reproducible on another pc (fedora silverblue up to date).

I got the idea to install the locale from these issue on libreoffice:  https://github.com/flathub/org.libreoffice.LibreOffice/issues/139 and especially https://github.com/flatpak/flatpak/issues/3061

But even if I try to reinstall edge it doesn't pull the locale runtime and I have to install it manually. Manually I install the following runtime, that fix the problem:

```
flatpak info runtime/org.freedesktop.Platform.Locale
          ID: org.freedesktop.Platform.Locale
         Ref: runtime/org.freedesktop.Platform.Locale/x86_64/21.08
        Arch: x86_64
      Branch: 21.08
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 1.3 GB

      Commit: 2a02a66d453326d5c0db4ec036cbba1af24d92bb33534fcc1f4f0bc13e002ee1
      Parent: f7b3955531cbb67d41cb25924acbd1d169ceb732005f164ad96ff7c002550d5c
     Subject: Export org.freedesktop.Platform.Locale
        Date: 2022-03-02 19:32:37 +0000
```

I will report back next Tuesday, but let me know if you need more info.

**Comment by refi64** [comment]
What's the output of `flatpak config`?

**Comment by seal20** [comment]
Hi,

First, I tried with a friend tat had a fedora system on which he never used any flatpak, and installing the edge flatpak pulled the locale runtime (partial though, I am not sure what it means), and he was able to open the file. So I think it may have been a problem on my system. But I don't know how. Anyway sorry for the noise.

My flatpak config is:
languages: *unset* (default: en)
extra-languages: *unset*

The fact that it is unset, may be a problem. I will check what it is set to on my friend pc.

Thanks for your help and dedication to the packaging of edge, although I use firefox as my main browser, it is useful to run online proprietary services.

Cheers

Sylvain

**Comment by refi64** [comment]
How was it you had set your language on your system?

**Comment by TheEvilSkeleton** [comment]
Closing this issue since there wasn't a response in the recent months.
