### ISSUE TITLE
App Not Found  No app with the ID com.microsoft.Edge was found on Flathub. Try searching for the app using the search bar above.

### ISSUE THREAD

**Issue by romulasry** [flathub/com.microsoft.Edge#13]
https://flathub.org/apps/details/com.microsoft.Edge

**Comment by TheEvilSkeleton** [comment]
That's normal. Edge is only available in the `beta` branch as of now. Flathub's website only fetches packages from the stable branch.

If you want to install the beta branch, run the following command:
```
flatpak remote-add flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
```

**Comment by romulasry** [comment]
Any idea on how long until they go to the main branch?

**Comment by TheEvilSkeleton** [comment]
I have no idea unfortunately. I am waiting on the Chrome flatpak to switch to stable since the Edge flatpak is based on the Chrome flatpak.
