### ISSUE TITLE
Unable to deploy in arch-chroot

### ISSUE THREAD

**Issue by ShobuPrime** [flathub/com.microsoft.Edge#149]
Executing: `/usr/bin/arch-chroot /mnt flatpak install --assumeyes flathub com.microsoft.Edge` provides the following error:

```
2022/05/18 02:45:10 shell.go:121: bwrap: pivot_root: Invalid argument
2022/05/18 02:45:10 shell.go:121: Warning: While trying to apply extra data: apply_extra script failed, exit status 256
2022/05/18 02:45:10 shell.go:121: bwrap: pivot_root: Invalid argument
2022/05/18 02:45:10 shell.go:121: Error: While trying to apply extra data: apply_extra script failed, exit status 256
2022/05/18 02:45:10 shell.go:121: error: Failed to install com.microsoft.Edge: While trying to apply extra data: apply_extra script failed, exit status 256
2022/05/18 02:45:10 shell.go:126: exit status 1
```

I'm able to install other flatpak browsers such as Brave via this method, but not Edge when I image a new machine.

**Comment by tinywrkb** [comment]
> I'm able to install other flatpak browsers such as Brave via this method, but not Edge when I image a new machine.

It's not the same installation process. This is a proprietary application that uses the apply_extra step, the other example you list doesn't.  
This is not a packaging issue. Use strace to figure out the failing syscall, and then fix the issue with your chroot.  

I highly recommend staying away from arch-chroot, this is a terrible tool to use for running containers. Only use it for deploying a new Arch Linux installation.  
The fact that [this](https://bugs.archlinux.org/task/61808) haven't been solved yet after over 3 years should tell you enough about running the tool on anything than a booted Arch Linux installation media environment.

**Comment by ShobuPrime** [comment]
Hello tinywrkb,

The reason why I'm using `arch-chroot` in the first place is because I'm am automating a fresh Arch Linux install.

Other Flatpaks use the `apply_extra` step which don't use bubblewrap to pivot root, and I think that's a part of the problem.

I wrote [this Arch Linux installer](https://github.com/ShobuPrime/ShobuArch) which handles Flatpaks, and I wanted Edge as a part of my software list to install unattended.

If you have a different suggestion I can use for unattended installations for a fresh Arch install, please let me know.

**Comment by tinywrkb** [comment]
> The reason why I'm using arch-chroot in the first place is because I'm am automating a fresh Arch Linux install.

It sounds like you can avoid the issue by simply running Flatpak in the host system environment.  
Read `man:flatpak(1)`, and make sure not to skip the `FLATPAK_SYSTEM_CACHE_DIR` entry.

> Other Flatpaks use the apply_extra step which don't use bubblewrap to pivot root, and I think that's a part of the problem.

This packaging expects a functioning Flatpak environment. Whatever issue you think exists, you introduced it yourself, and it's clearly not a packaging issue.  

> If you have a different suggestion I can use for unattended installations for a fresh Arch install, please let me know.

As said, add Flatpak to your installation media.  

An alternative is to preload the installation media with Flatpak applications and deploy them. I use this method, specifically I have a btrfs subvolume for Flatpak apps and copy it with btrfs-send/receive, but you can choose the `create-usb` method, see `man:flatpak-create-usb(1)`.  
I have no idea if `create-usb` support applications that use `apply_extra`, though I suspect that it should matter.  
The benefits of this approach are being able to deploy a system without networking, and running the apps directly from the live media.

You could also try running in a different container environment. Try systemd-nspawn, and make sure to read the section about `--capability` in `man:systemd-nspwan(1)`, and `man:capabilities(7)`.

**Comment by ShobuPrime** [comment]
Hey @tinywrkb , I wanted to follow up and say thank you for the `systemd-nspawn` suggestion. It ended up being the solution for me to automate installing all Flatpaks from a Fresh ISO install.

Fun fact, the default mount option similar to `chroot` or `arch-chroot` would still fail. I needed to fully boot the container such as `systemd-nspawn -nb -D /mnt` and place an autorun script for this  to behave as expected.

You can see how I did it in [this commit](https://github.com/ShobuPrime/ShobuArch/commit/0ae9aef7eea318e028d6e69cafd68b69cecbb6f1)

**Comment by tinywrkb** [comment]
I'm glad you find something that works for you.  
I think you should still consider adding Flatpak to your installation media and avoid the container. I would go with the simpler solution.
