### ISSUE TITLE
WASM does not seem to work

### ISSUE THREAD

**Issue by Jeffrey-de-Bruijn** [flathub/com.microsoft.Edge#169]
On RHEL 9

`no native wasm support detected`

**Comment by Jeffrey-de-Bruijn** [comment]
> Does it work on browsers provided by system package managers?

Yes, tested on firefox shipped by red hat's repositories

**Comment by evan-a-a** [comment]
I ran into this recently too, on Fedora 36. The Mozilla's Firefox flatpak and the native Firefox supports WASM without any issues.

**Comment by evan-a-a** [comment]
Quick update, this is probably due to the "enhanced security protections" that Microsoft enables. You can turn it off by pulling up the site information from the address bar, opening "Enhance Security for this site" and switching it off to add an exception to the rules.
