### ISSUE TITLE
Metainfo parse error prevents upstream data update

### ISSUE THREAD

**Issue by gasinvein** [flathub/com.microsoft.Edge#17]
Looks like Python XML library doesn't like xml files starting with comment: flathub/flatpak-external-data-checker#128
Until we figure out why, if you want automated updates via the external data checker - consider moving the copyright comment in `.metainfo.xml` to the second line.

**Comment by gasinvein** [comment]
Oh, you've already committed flathub/com.microsoft.Edge@095435d47eda5ce1a34663a575d09cfe99397c1f while I was writing this. Thanks and sorry for the noise.

**Comment by TheEvilSkeleton** [comment]
Don't worry. I appreciate the very quick feedback.
