### ISSUE TITLE
Not available through Flathub

### ISSUE THREAD

**Issue by makkussu** [flathub/com.microsoft.Edge#18]
Hi there!

I have recently found this flatpak and wanted to try it out. I've followed the link in repository's 'About' part ([This one](https://flathub.org/apps/details/com.microsoft.Edge)) but it is not available there. Was there any reason for flatpak removal from official website?

**Comment by TheEvilSkeleton** [comment]
That's because flathub.org doesn't fetch from the `beta` repos, just like Chrome and Brave flatpaks.

See https://github.com/flathub/com.microsoft.Edge/issues/13#issuecomment-774723570

**Comment by makkussu** [comment]
Oh, thanks. I apologize for not checking the issue threads
