### ISSUE TITLE
How do I make Edge trust a self-signed certificate?

### ISSUE THREAD

**Issue by Jeffrey-de-Bruijn** [flathub/com.microsoft.Edge#183]
I tried adding a full-chain .pem self-signed certificate in edge://settings/privacy/manageCertificates but it doesn't seem like Edge is ok with it. Do I have to mount the system's certificate directory?

**Comment by TheEvilSkeleton** [comment]
I'm gonna be honest. I have no idea how self-signed certificates work. Perhaps this is related with https://github.com/flathub/com.google.Chrome/pull/150?

**Comment by tinywrkb** [comment]
For user supplied certificates, I believe that the only issue is that `.pki` folder isn't saved between application session, and possible workarounds to this are documented in the linked issue, though Google or Igalia should really fix already, and respect the XDG base dir spec.

> Do I have to mount the system's certificate directory?

I'm not quite sure about system certificates, if that what you mean. My best guess is to bind mount the system `/etc` folder onto `/run/host/etc` in the sandbox by adding the `--filesystem=host-etc` override, and then set the `SSL_CERT_DIR` and/or `SSL_CERT_FILE` environment variables to pick up the system certs.  
For more details, see `man:openssl-env(7)` and `man:SSL_CTX_load_verify_locations(3)`.
