### ISSUE TITLE
Instant crash on Steam Deck

### ISSUE THREAD

**Issue by KAMiKAZOW** [flathub/com.microsoft.Edge#238]
```
flatpak run com.microsoft.Edge 

(process:2): Gtk-WARNING **: 23:12:44.943: Locale not supported by C library.
        Using the fallback 'C' locale.
Gtk-Message: 23:12:44.944: Failed to load module "canberra-gtk-module"
Stub sandbox ignoring command: /app/extra/nacl_helper
[2:2:1219/231245.167599:ERROR:nacl_fork_delegate_linux.cc(313)] Bad NaCl helper startup ack (0 bytes)
Gtk-Message: 23:12:45.442: Failed to load module "canberra-gtk-module"
[2:2:1219/231245.514787:ERROR:object_proxy.cc(623)] Failed to call method: org.kde.KWallet.isEnabled: object_path= /modules/kwalletd5: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
[2:2:1219/231245.514811:ERROR:kwallet_dbus.cc(100)] Error contacting kwalletd5 (isEnabled)
[2:2:1219/231245.515259:ERROR:object_proxy.cc(623)] Failed to call method: org.kde.KLauncher.start_service_by_desktop_name: object_path= /KLauncher: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
[2:2:1219/231245.515281:ERROR:kwallet_dbus.cc(72)] Error contacting klauncher to start kwalletd5
[2:2:1219/231245.515569:ERROR:object_proxy.cc(623)] Failed to call method: org.kde.KWallet.close: object_path= /modules/kwalletd5: org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
[2:2:1219/231245.515581:ERROR:kwallet_dbus.cc(418)] Error contacting kwalletd5 (close)
[2:2:1219/231245.547834:ERROR:assistance_home_client.cc(32)] File path /home/deck/.var/app/com.microsoft.Edge/config/microsoft-edge/Default
[1219/231245.674750:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
```

Using SteamOS 3.4 from the preview channel.

**Comment by TheEvilSkeleton** [comment]
Does Google Chrome launch for you?

**Comment by Etaash-mathamsetty** [comment]
> Does Google Chrome launch for you?

yes, im getting a similar issue and chrome's flatpak is working

**Comment by Etaash-mathamsetty** [comment]
ok I was able to fix it by going to discover, uninstalling, clearing app data, and then reinstalling

**Comment by Etaash-mathamsetty** [comment]
> how do I clear app data?
> 

There should be a button after you uninstall the app

**Comment by dPandl** [comment]
found the button but it didnt work for me. I get that little loading animation on the cursor and than it crashes :(

**Comment by TigerBeanst** [comment]
I found the only way to start Edge is open it from Steam....

**Comment by dPandl** [comment]
I never tried to launch it through steam in desktop mode. Thats very weird but thanks for the help, now i can at least launch it

**Comment by KAMiKAZOW** [comment]
Considering how the issue is affecting other people who have no clue about bug reports here, I strongly suggest to find a solution that can be shipped as part of the Flathub package:
![image](https://user-images.githubusercontent.com/3259076/209446482-eedf1197-eb89-4149-8a76-56e206655673.png)

**Comment by Etaash-mathamsetty** [comment]
I am not exactly sure what causes the problem
1. it's proprietary software (hard to debug)
2. im on KDE as well and it works fine on kde wayland at least (by reinstalling and resetting app data)

Not sure how we are supposed to debug this

**Comment by KAMiKAZOW** [comment]
If it works being launched from Steam but being launched normally, chances are there is some incompatibility with SteamOS 3.4 whereas launching from Steam makes it use an Ubuntu 12.04 or Debian 10-based runtime bundle.

What puzzles me a bit is that Flatpak is supposed to no not be affected by that because it has its own runtime bundles. Does a Flatpak application perhaps use host OS dependencies if they are not specified by the Flatpak package definition? Would it be too complicated to repackage the RPM instead of the DEB to see if that makes a difference?

**Comment by Etaash-mathamsetty** [comment]
> If it works being launched from Steam but being launched normally, chances are there is some incompatibility with SteamOS 3.4 whereas launching from Steam makes it use an Ubuntu 12.04 or Debian 10-based runtime bundle.
> 
> What puzzles me a bit is that Flatpak is supposed to no not be affected by that because it has its own runtime bundles. Does a Flatpak application perhaps use host OS dependencies if they are not specified by the Flatpak package definition? Would it be too complicated to repackage the RPM instead of the DEB to see if that makes a difference?

The best part is that I use arch linux, just like the way steam OS does, so I have an even fainter idea of what is causing the problem

**Comment by TheEvilSkeleton** [comment]
> What puzzles me a bit is that Flatpak is supposed to no not be affected by that because it has its own runtime bundles. Does a Flatpak application perhaps use host OS dependencies if they are not specified by the Flatpak package definition? Would it be too complicated to repackage the RPM instead of the DEB to see if that makes a difference?

I can only speculate, but I would assume that SteamOS is _too_ bare bones. Flatpak depends on the host system for information, like graphics drivers. Flatpak detects those information to install their Flathub equivalents, e.g. [`org.freedesktop.Platform.GL.nvidia`](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia) if you have NVIDIA drivers installed on the host system. If you don't have the drivers, but you still have an NVIDIA GPU in your system, then Flatpak will struggle with installing the correct drivers. It's an ugly workaround, but essentially the only meaningful way to get information (and contain them). It might be that SteamOS is too bare bones and doesn't contain enough information for Flatpak to detect, but the Ubuntu 12.04 base does.

Again, it's all speculation. I have absolutely no idea how SteamOS works (I wish I had a Steam Deck, to learn more about it). If I'm wrong with SteamOS, please correct me.

**Comment by deafboy** [comment]
Similar issue on elementary 6.1 (based on Ubuntu focal)

```
[deafboy@DeafboyLatitude7420 ~]$ flatpak run com.microsoft.Edge 

(process:2): Gtk-WARNING **: 18:56:17.231: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 18:56:17.263: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:56:17.265: Failed to load module "canberra-gtk-module"
Stub sandbox ignoring command: /app/extra/nacl_helper
[2:2:1228/185617.558474:ERROR:nacl_fork_delegate_linux.cc(313)] Bad NaCl helper startup ack (0 bytes)
Gtk-Message: 18:56:17.674: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:56:17.675: Failed to load module "canberra-gtk-module"
[1228/185617.951602:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
[2:2:0100/000000.966397:ERROR:zygote_linux.cc(622)] Zygote could not fork: process_type renderer numfds 5 child_pid -1
[2:2:0100/000000.966494:ERROR:zygote_linux.cc(654)] write: Broken pipe (32)
[deafboy@DeafboyLatitude7420 ~]$ 
```

**Comment by KAMiKAZOW** [comment]
> I can only speculate, but I would assume that SteamOS is _too_ bare bones. Flatpak depends on the host system for information, like graphics drivers. Flatpak detects those information to install their Flathub equivalents, e.g. [`org.freedesktop.Platform.GL.nvidia`](https://github.com/flathub/org.freedesktop.Platform.GL.nvidia) if you have NVIDIA drivers installed on the host system. If you don't have the drivers, but you still have an NVIDIA GPU in your system, then Flatpak will struggle with installing the correct drivers.

SteamOS comes with complete KDE Plasma Desktop, everything else runs and Steam Deck has no NVidia GPU. If anything is barebones, it's the two Steam Linux Runtime bundles.

I'm happy to provide any log I can, just tell me how to produce it.

Has the idea to switch to the RPM package even been entertained to look if that works any better?

**Comment by Etaash-mathamsetty** [comment]
maybe you guys don't have permission to run ptrace
what does `cat /proc/sys/kernel/yama/ptrace_scope` output

**Comment by holdenger** [comment]
I found out that if you guys have locales other than C or en_US.UTF-8, Edge will crash. If you don't want to change your locales in Desktop Manager (like KDE, or Gnome), you can add own env variable to flatpak command `--env=LC_ALL=en_US.UTF-8` so the complete command to run Edge will look like this:
`/usr/bin/flatpak run --env=LC_ALL=en_US.UTF-8 --branch=stable --arch=x86_64 --command=/app/bin/edge --file-forwarding com.microsoft.Edge @@u %U @@`

**Comment by TheEvilSkeleton** [comment]
Fixed by https://github.com/flathub/com.microsoft.Edge/pull/247
