### ISSUE TITLE
Edge crash when launching from the desktop entry

### ISSUE THREAD

**Issue by Jailoris** [flathub/com.microsoft.Edge#242]
Edge open and crash a few seconds after, running on Gnome Wayland, there is a loading spinner next to it while it is running :

![Capture d’écran du 2023-01-10 18-30-10](https://user-images.githubusercontent.com/98796232/211718418-b5e0ceac-0a37-4205-811d-f9bdad73d040.png)

Launching it from the terminal work fine and I'm even able to launch new instances with the desktop entry after summoning it from the terminal. There is also no loading spinner when launching it from the terminal.

**Comment by Jailoris** [comment]
Here is a log of journalctl when launching Edge from the desktop entry :

`janv. 10 18:36:37 archlinux systemd[1330]: Started Application launched by gnome-shell.
janv. 10 18:36:38 archlinux systemd[1330]: Started app-flatpak-com.microsoft.Edge-7056.scope.
janv. 10 18:36:38 archlinux cobalt[7069]: Failed to load module "canberra-gtk-module"
janv. 10 18:36:38 archlinux cobalt[7069]: Failed to load module "canberra-gtk-module"
janv. 10 18:36:38 archlinux systemd[1330]: Started app-flatpak-com.microsoft.Edge-7097.scope.
janv. 10 18:36:38 archlinux com.microsoft.Edge.desktop[7076]: Stub sandbox ignoring command: /app/extra/nacl_helper
janv. 10 18:36:38 archlinux com.microsoft.Edge.desktop[7077]: [2:2:0110/183638.348388:ERROR:nacl_fork_delegate_linux.cc(313)] Bad NaCl helper startup ack (0 bytes)
janv. 10 18:36:38 archlinux com.microsoft.Edge.desktop[7077]: Gtk-Message: 18:36:38.549: Failed to load module "canberra-gtk-module"
janv. 10 18:36:38 archlinux com.microsoft.Edge.desktop[7077]: Gtk-Message: 18:36:38.550: Failed to load module "canberra-gtk-module"
janv. 10 18:36:38 archlinux gnome-keyring-daemon[1346]: asked to register item /org/freedesktop/secrets/collection/login/1, but it's already registered
janv. 10 18:36:38 archlinux gnome-keyring-d[1346]: asked to register item /org/freedesktop/secrets/collection/login/1, but it's already registered
janv. 10 18:36:38 archlinux com.microsoft.Edge.desktop[7077]: [2:2:0110/183638.624724:ERROR:assistance_home_client.cc(32)] File path /home/heimana/.var/app/com.microsoft.Edge/config/microsoft-edge/Default
janv. 10 18:36:38 archlinux gnome-shell[1576]: Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x5612d6484a80] is on because it needs an allocation.
janv. 10 18:36:38 archlinux gnome-shell[1576]: Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x5612d7e1e6e0] is on because it needs an allocation.
janv. 10 18:36:38 archlinux com.microsoft.Edge.desktop[7077]: [2:2:0110/183638.778767:ERROR:nacl_browser.cc(288)] Failed to open NaCl IRT file "/app/extra/nacl_irt_x86_64.nexe": -4
janv. 10 18:36:40 archlinux systemd[1330]: Started app-flatpak-com.microsoft.Edge-7397.scope.
janv. 10 18:36:41 archlinux com.microsoft.Edge.desktop[7077]: [54:351:0110/183641.505640:ERROR:vaapi_video_decoder.cc(1206)] failed Initialize()ing the frame pool
janv. 10 18:36:41 archlinux com.microsoft.Edge.desktop[7077]: [54:54:0110/183641.591369:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: RED_8, share_between_threads: 0, gmb_type: shared_memory
janv. 10 18:36:41 archlinux com.microsoft.Edge.desktop[7077]: [54:54:0110/183641.591545:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: RG_88, share_between_threads: 0, gmb_type: shared_memory
janv. 10 18:36:41 archlinux com.microsoft.Edge.desktop[7077]: [54:54:0110/183641.598679:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: RED_8, share_between_threads: 0, gmb_type: shared_memory
janv. 10 18:36:41 archlinux com.microsoft.Edge.desktop[7077]: [54:54:0110/183641.598826:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: RG_88, share_between_threads: 0, gmb_type: shared_memory
janv. 10 18:36:41 archlinux com.microsoft.Edge.desktop[7077]: [54:54:0110/183641.601537:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: RED_8, share_between_threads: 0, gmb_type: shared_memory
janv. 10 18:36:41 archlinux com.microsoft.Edge.desktop[7077]: [54:54:0110/183641.601685:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: RG_88, share_between_threads: 0, gmb_type: shared_memory
janv. 10 18:36:41 archlinux com.microsoft.Edge.desktop[7077]: [54:54:0110/183641.604903:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: RED_8, share_between_threads: 0, gmb_type: shared_memory
janv. 10 18:36:41 archlinux com.microsoft.Edge.desktop[7077]: [54:54:0110/183641.610507:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: RG_88, share_between_threads: 0, gmb_type: shared_memory
janv. 10 18:36:41 archlinux com.microsoft.Edge.desktop[7077]: [54:54:0110/183641.610693:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: RED_8, share_between_threads: 0, gmb_type: shared_memory
janv. 10 18:36:41 archlinux com.microsoft.Edge.desktop[7077]: [54:54:0110/183641.610834:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: RG_88, share_between_threads: 0, gmb_type: shared_memory
janv. 10 18:36:41 archlinux com.microsoft.Edge.desktop[7077]: [54:54:0110/183641.623489:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: RED_8, share_between_threads: 0, gmb_type: shared_memory
janv. 10 18:36:41 archlinux com.microsoft.Edge.desktop[7077]: [54:54:0110/183641.623687:ERROR:shared_image_factory.cc(575)] Could not find SharedImageBackingFactory with params: usage: Gles2|Raster|DisplayRead|Scanout, format: RG_88, share_between_threads: 0, gmb_type: shared_memory
janv. 10 18:36:41 archlinux com.microsoft.Edge.desktop[7077]: [59:65:0110/183641.639706:ERROR:ssl_client_socket_impl.cc(1150)] handshake failed; returned -1, SSL error code 1, net_error -101
janv. 10 18:36:41 archlinux com.microsoft.Edge.desktop[7077]: [59:65:0110/183641.661732:ERROR:ssl_client_socket_impl.cc(1150)] handshake failed; returned -1, SSL error code 1, net_error -101
janv. 10 18:36:45 archlinux com.microsoft.Edge.desktop[7077]: [59:65:0110/183645.014791:ERROR:ssl_client_socket_impl.cc(1150)] handshake failed; returned -1, SSL error code 1, net_error -100
janv. 10 18:36:45 archlinux com.microsoft.Edge.desktop[7077]: [59:65:0110/183645.031076:ERROR:ssl_client_socket_impl.cc(1150)] handshake failed; returned -1, SSL error code 1, net_error -100
janv. 10 18:36:48 archlinux systemd[1330]: app-flatpak-com.microsoft.Edge-7097.scope: Consumed 7.600s CPU time.
`

**Comment by TheEvilSkeleton** [comment]
Fixed by https://github.com/flathub/com.microsoft.Edge/pull/247
