### ISSUE TITLE
Security Keys are not Working

### ISSUE THREAD

**Issue by Nature1Limited** [flathub/com.microsoft.Edge#295]
Hello, 
I want to use my YubiKey to log into my Microsoft account, but it doesn't recognize the security key.
Other websites with FIDO support do not work on this Version of Microsoft Edge as well. 

I am confident that this is not a problem with Flatpak or my YubiKey, because I installed Google Chrome as a Flatpak and there it works perfectly.  

OS: Manjaro
KDE 5.26.5
Flatpak 1.15.2

**Comment by evan-a-a** [comment]
Are you still experiencing this issue? I haven't had problems using my YubiKey with Edge.
