### ISSUE TITLE
Edge can't display CJK fonts

### ISSUE THREAD

**Issue by junjieyuan** [flathub/com.microsoft.Edge#299]
All Chinese fonts are displayed as boxes, and ASCII display is normal.

System: Fedora Linux 38.20230414.n.0 (Silverblue)

Workaround:

```sh
# copy Chinese fonts from host to flatpak container 
cp -R /usr/share/fonts/google-noto-sans-cjk-vf-fonts  ~/.var/app/com.microsoft.Edge/data/fonts
```

See also: flathub/com.google.Chrome#202

**Comment by Pryka** [comment]
Same for me, no CJK fonts.

**Comment by Pryka** [comment]
Any news on that? I'm on Silverblue 38 all is up to date.

Still no CJK fonts.

**Comment by evan-a-a** [comment]
Does the solution mentioned in https://github.com/flathub/org.chromium.Chromium/issues/280#issuecomment-1542623745 work people? It seems to have fixed it for me. I'm inclined to close this issue if so.

**Comment by Pryka** [comment]
I think it was fixed somewhere upstream, because I didn't do anything and my fonts are fine. No idea when this happened though.
