### ISSUE TITLE
Most of the page crash with error code 4

### ISSUE THREAD

**Issue by huyhoang160593** [flathub/com.microsoft.Edge#303]
![image](https://user-images.githubusercontent.com/41776348/233430290-f8ab0f7d-7d0a-48bd-99c1-79761199d771.png)
Most of the page I visited became something like this, I can't open devtools, nothing. so frustrating 

OS: Fedora 37
Flatpak: 1.14.4
Microsoft Edge Version: 112.0.1722.54 (Official build)

**Comment by evan-a-a** [comment]
This is related to #304

**Comment by evan-a-a** [comment]
Should be resolved.
