### ISSUE TITLE
Wayland fractional scaling is buggy with v113

### ISSUE THREAD

**Issue by TheComputerM** [flathub/com.microsoft.Edge#319]
The UI scaling looks fine, but the app behaves as if the scaling is 2x instead of 1.5x, example cursor is larger, and it is not in the position it appears to be.

https://bugs.chromium.org/p/chromium/issues/detail?id=1356014
https://github.com/flathub/org.chromium.Chromium/commit/eea7af903decb3a3b9bb6fdacbb55d24a90e18f3

Same issue with brave v113

**Comment by TheComputerM** [comment]
Fractional scaling is not an issue with the latest chromium flatpak.

**Comment by evan-a-a** [comment]
Wayland issues are an upstream problem and not related to the flatpak. X11 remains the default for Edge until upstream swaps to wayland by defualt.
