### ISSUE TITLE
Seeking for new maintainer

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub/com.microsoft.Edge#348]
I'm burned out and don't feel like maintaining the Edge flatpak anymore. There are several merge requests that need to be reviewed, but I'm unmotivated to go through them. Is anybody willing to replace my role as a maintainer for the Edge flatpak?

/cc @tinywrkb (you've done substantial contributions) @eyenpi (maintainer of [com.microsoft.EdgeDev](https://github.com/flathub/com.microsoft.EdgeDev))

**Comment by orowith2os** [comment]
I'd be interested in being there to keep a general eye on things, and merging PRs when needed. Anything more significant may require someone else to review.

**Comment by ItsJamie9494** [comment]
:wave: if needed, let me know

**Comment by TheEvilSkeleton** [comment]
Is it okay if I ask the Flathub maintainers to send an invite to both of you?

**Comment by orowith2os** [comment]
Go for it! That's the standard procedure after all.

**Comment by TheEvilSkeleton** [comment]
@barthalion sorry for the ping and I know you're busy at the time, but when you're back, could you add the people above as collaborators? Thanks.

**Comment by TheEvilSkeleton** [comment]
Thanks! I'm closing the issue
