### ISSUE TITLE
Edge Beta or Edge Dev?

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flathub/com.microsoft.Edge#37]
https://www.xda-developers.com/microsofts-edge-browser-is-now-available-in-beta-for-linux/

MS Edge Beta just came out and is available on Linux. Should we stick with Dev builds or switch to Beta builds?

**Comment by TuxKruger** [comment]
IMO Beta build would be better. As the the post says, "That means that if you’re on Linux or even for Chromebooks, you can test a more **stable** version of the browser."

**Comment by tinywrkb** [comment]
Switch to beta. The latest 91.x dev builds were pretty good. They had sync working, import fixed, and no major issue as far as I can tell.  
This package should switch to stable when/if it will be available.  

I think that in the long run, stable builds should be set on the master branch, beta builds on the beta branch, and dev builds as a separate Flatpak app.

**Comment by second2050** [comment]
IMO default should be the Beta channel but also keep the Dev channel available as a seperate flatpak (think: `com.microsoft.Edge.dev`).

The Beta channel should use `com.microsoft.Edge.beta` as the package name though.

**Comment by TheEvilSkeleton** [comment]
For now I will only switch from Dev to Beta.

As for the Dev builds, I'll contact (again) Microsoft and ask if they can maintain the Flatpak package. If they can, I'll talk to them about releasing `com.microsoft.Edge.dev`.
