### ISSUE TITLE
Cannot login into a different microsoft account in second profile

### ISSUE THREAD

**Issue by Ciberbago** [flathub/com.microsoft.Edge#386]
Hi! I don't know if this is the right place, but I have a problem with edge in the flatpak version. 

Whenever I try to use a second profile and login with another Microsoft account... for example: "Main profile using account1@outlook.com" and wanting to login with "account2@outlook.com" into a second profile... opens the login pop up, then redirects me to the main profile saying something along the lines of "Opening this in personal profile" with 2 options of "Open in second profile" or "Stay here" but neither of those work or do anything. Then... in the second profile nothing happens, and I can't log in.

I can't find information about this in the web, that's why I ask here, sorry if it's not the place for it and thank you in advance.

**Comment by evan-a-a** [comment]
Can you confirm that this works fine on the non-Flatpak Edge? I'm inclined to think this is an Edge issue stemming from the new work/personal profile auto-switch feature.

**Comment by Ciberbago** [comment]
You know? It never occurred to me to try that. I used the microsoft-edge-stable-bin version from the AUR and it does not work either. Sorry for the trouble.

**Comment by evan-a-a** [comment]
No worriee. Thanks for checking!
