### ISSUE TITLE
custom flags on Tumbleweed not working via suggested method

### ISSUE THREAD

**Issue by catbabylon** [flathub/com.microsoft.Edge#393]
The suggested method to pass custom flags via the .conf file doesn't seem to work with MS Edge flatpak on Tumbleweed.

At least as far as using them to get wayland native to work. I managed to get it to work by adding the flags to the .desktop file. Having switched to Fedora, the suggested method does work fine, so I assume there is something amiss with the way Opensuse was working?

**Comment by evan-a-a** [comment]
That sounds like a SUSE-ism. I am not familiar with SUSE and how it differs from Fedora et. all, but I can't reproduce this on Fedora or Ubuntu. I don't think there's anything actionable here for the package itself.
