### ISSUE TITLE
Any way to enable hardware acceleration for video decode?

### ISSUE THREAD

**Issue by paradoxicpotato** [flathub/com.microsoft.Edge#51]
I checked `edge://gpu` and noticed that hardware acceleration for video decode wasn't enabled. Is there a way i can enable this?

**Comment by tinywrkb** [comment]
Getting the feature to be green is pretty easy, just follow the [Chromium page on the Arch Linux Wiki](https://wiki.archlinux.org/title/Chromium#Hardware_video_acceleration).  
That being said, I don't think VAAPI is enabled in the build as I couldn't get it to work, so even if the `edge://gpu` says that it's enabled, it not really meaningful.  
Also, AFAIK, currently, VAAPI only works with the old X11 backend, [not with Ozone X11](https://bugs.chromium.org/p/chromium/issues/detail?id=1121948) nor with Ozone Wayland.

**Comment by TheEvilSkeleton** [comment]
Credit to https://www.linuxuprising.com/2021/01/how-to-enable-hardware-accelerated.html: you need to pass the `--enable-features=VaapiVideoDecoder` flag on X11, or `--use-gl=egl --enable-features=VaapiVideoDecoder,UseOzonePlatform --ozone-platform=wayland` flags on Wayland backend.

Using `--use-gl=egl --enable-features=VaapiVideoDecoder` on Wayland (so with Xwayland) did cause a lot of issues for me, but using on a Wayland backend worked completely fine for me so mileage may vary.

If you want to run it everytime you launch from an app menu, you can put the custom flags in `~/.var/app/com.microsoft.Edge/config/edge-flags.conf`, where each flag is in a separate line.

Does this help?

**Comment by tinywrkb** [comment]
@TheEvilSkeleton did you confirmed that Edge is using VpxVideoDecoder or MojoVideoDecoder and not FFmpegVideoDecoder?  
It never worked for me correctly in Edge.

**Comment by TheEvilSkeleton** [comment]
I just checked and it looks like none of what you mentioned is being used.

![image](https://user-images.githubusercontent.com/50847364/122480833-9a449b00-cf9b-11eb-9210-d10a70ff8afd.png)

**Comment by tinywrkb** [comment]
> I thought edge://flags was the only way to tell

You need to confirm that HW acceleration actually used when playing videos and `edge://flags` won't tell you that.

From your screen capture of the Media devtool it looks like VpxVideoDecoder is used and this confirms that VAAPI works for you. Is this Ozone Wayland?

For me, it's completely broken.

**Comment by TheEvilSkeleton** [comment]
> You need to confirm that HW acceleration actually used when playing videos and `edge://gpu` won't tell you that.

Oh right, I completely forgot to mention that. It shows that Hardware decode is accelerated:

![image](https://user-images.githubusercontent.com/50847364/122483350-5f913180-cfa0-11eb-8f59-aeb544f9da15.png)

> From your screen capture of the Media devtool it looks like VpxVideoDecoder is used and this confirms that VAAPI works for you. Is this Ozone Wayland?

Yes, although it works on XWayland too.

**Comment by tinywrkb** [comment]
I see that you don't have HW accelerated rasterization and out-of-process rasterization enabled.

![swappy-20210618-022719](https://user-images.githubusercontent.com/44030034/122484270-f1b72b00-cfdc-11eb-8ef0-f075c794b632.png)

Do you have zero-copy enabled and using HW GPU memory buffers?

![swappy-20210618-022607](https://user-images.githubusercontent.com/44030034/122484328-0e536300-cfdd-11eb-81e9-5d58a03fdcf7.png)

**Comment by tinywrkb** [comment]
I gave this another look and got VAAPI working. I had to package libva 2.11.0 to make it work.  
I actually now noticing that this is a regression affecting Chromium-based browsers.  
Surprisingly VAAPI works even in Ozone X11 and Ozone Wayland. The last time I checked, in Chrome and Chromium it only worked with the old X11 backend.  

There are [merged backported patches for libva in the runtime to fix DRM authentication](https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/5069), but I guess they are irrelevant for this, though they still should be mentioned.  
It should be noted that I have VAAPI working correctly with media players, at least MPV and derivatives at least.

@TheEvilSkeleton what are the versions of mesa and libva on your host?  
On my system, it's mesa 21.1.2 and libva 2.11.0.

**Comment by TheEvilSkeleton** [comment]
> Do you have zero-copy enabled and using HW GPU memory buffers?

I didn't have when I sent the screenshot, but I do now.

> @TheEvilSkeleton what are the versions of mesa and libva on your host?
On my system, it's mesa 21.1.2 and libva 2.11.0.

I have mesa 21.1.1 and libva 2.11.0.

---

I added `--force-gpu-rasterization` flag, and enabled edge://flags/#enable-gpu-rasterization and edge://flags/#enable-zero-copy:

![image](https://user-images.githubusercontent.com/50847364/122488358-52c60b00-cfab-11eb-99e2-0169db86f484.png)

![image](https://user-images.githubusercontent.com/50847364/122488391-5fe2fa00-cfab-11eb-8041-ed69e0aa94c1.png)

**Comment by tinywrkb** [comment]
> I have mesa 21.1.1 and libva 2.11.0.

Then it's not much different from my host OS.

**Comment by paradoxicpotato** [comment]
> Credit to https://www.linuxuprising.com/2021/01/how-to-enable-hardware-accelerated.html: you need to pass the `--enable-features=VaapiVideoDecoder` flag on X11, or `--use-gl=egl --enable-features=VaapiVideoDecoder,UseOzonePlatform --ozone-platform=wayland` flags on Xwayland.
> 
> Using `--use-gl=egl --enable-features=VaapiVideoDecoder` on Wayland (so with Xwayland) did cause a lot of issues for me, but using on a Wayland backend worked completely fine for me so mileage may vary.
> 
> If you want to run it everytime you launch from an app menu, you can put the custom flags in `~/.var/app/com.microsoft.Edge/config/edge-flags.conf`, where each flag is in a separate line.
> 
> Does this help?

Yeah using `--use-gl=egl --enable-features=VaapiVideoDecoder,UseOzonePlatform --ozone-platform=wayland` on wayland works like a dream for me. That alongside enabling gpu rasterization and zero copy made the browsing experience really smooth. Since this seems to work i'll go ahead and close the issue, thanks for the help!

**Comment by vchernin** [comment]
This is a bit of an older post, but I'd highly recommend not relying on edge://gpu (or chrome://gpu) as I've never found it reliable.

`kVideoDecoderName` listing MojoVideoDecoder in edge or chrome://media-internals/ means your gpu's hardware video decoder is being used to play a video. You might also see VideoDecode Accelerator or GpuVideoDecoder if on an older or newer Chromium build (I can't remember). If anything but those 3 are present, hardware gpu video decoding is not being used.

I'd recommend instead of relying on Chromium/Edge to look at usage directly.

Confirm gpu hardware video decode usage on Intel by installing `intel-gpu-tools` and running `sudo intel_gpu_tools`, the video bar shows hardware video decode usage. AMD has `radeontop`, not sure how useful it is since I don't have AMD hardware.

--use-gl=egl and ozone/wayland will help here as the rendering is more efficient, but that doesn't mean the video is being hardware decoded.

I've never gotten hardware video decoding in Chromium working on Wayland, I've only gotten [Firefox](https://wiki.archlinux.org/title/Firefox#Hardware_video_acceleration) to work but that has sandboxing issues.
