### ISSUE TITLE
Touchpad gestures not working

### ISSUE THREAD

**Issue by ominoussage** [flathub/com.microsoft.Edge#557]
On Firefox, you can perform a two-finger, vertically aligned swipe to either left or right that goes to the previous or next page, which I find really helpful. There's the "swipe between pages" option from settings that should be doing that, but the gesture does not work regardless of it turned on or off.

Tested on both Xorg and Wayland, doesn't work. Running Fedora Silverblue 39.
Edge version is 129.0.2792.65

**Comment by evan-a-a** [comment]
This doesn't appear to work properly on the non-flatpak'ed version of Edge, so it's likely a Chromium or Edge problem, not one from the flatpak.

**Comment by evan-a-a** [comment]
It's a chromium issue. I can't get the gestures to work on Chrome for Linux either. Closing since there's nothing the flatpak can do about it.
