### ISSUE TITLE
Add master branch for stable version of Microsoft Edge

### ISSUE THREAD

**Issue by prateekmedia** [flathub/com.microsoft.Edge#88]
Microsoft edge is now available in stable branch since 29 October, This flatpak should add a master branch to package the stable version in the stable channel of flathub.

Link: https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/

**Comment by cho2** [comment]
https://github.com/flathub/com.microsoft.Edge/pull/86#issuecomment-955184915

**Comment by prateekmedia** [comment]
@cho2 So should I close the issue then?

**Comment by TheEvilSkeleton** [comment]
I'm going to reopen and pin this issue so others don't miss this issue.

**Comment by da2x** [comment]
@TheEvilSkeleton don’t you need to update apply_extra.sh to use stable as well?

**Comment by TheEvilSkeleton** [comment]
Yes.

**Comment by TheEvilSkeleton** [comment]
Good news, [Chrome is now available on Flathub stable](https://flathub.org/apps/details/com.google.Chrome)! @refi64 asked us privately to keep Edge and Brave on beta for about a week. Hopefully Edge and Brave should be available by then.

**Comment by TheEvilSkeleton** [comment]
Sorry for the delay everyone! I finally pushed Edge on the `master` branch! https://github.com/flathub/com.microsoft.Edge/commit/502076a3cce63879b1e25d1c6a31c56a6ca8ed47

Edge should be published within 4 hours at the time of writing this comment. I will close this issue, enjoy everyone!
