### ISSUE TITLE
Can't connect to `Persepolis Download manager` using extension

### ISSUE THREAD

**Issue by prateekmedia** [flathub/com.microsoft.Edge#90]
When using [Persepolis download manager(PDM) extension](https://chrome.google.com/webstore/detail/persepolis-download-manag/legimlagjjoghkoedakdjhocbeomojao?hl=en), this(and maybe other chromium flatpak's) fails to connect to PDM.

Does any talk name or other steps are needed for that, As I know PDM uses aria2 and I can't find out any info why it can't connect to msedge flatpak.

**Comment by TheEvilSkeleton** [comment]
Sadly I have no control over this. It requires Native Messaging which isn't available in Flatpak. For reference, Firefox has this issue too: https://bugzilla.mozilla.org/show_bug.cgi?id=1621763. Sorry, I will have to close this.
